// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/public/todo/v1/todo.proto

package todov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListTodosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTodosRequest) Reset() {
	*x = ListTodosRequest{}
	mi := &file_proto_public_todo_v1_todo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTodosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTodosRequest) ProtoMessage() {}

func (x *ListTodosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_public_todo_v1_todo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTodosRequest.ProtoReflect.Descriptor instead.
func (*ListTodosRequest) Descriptor() ([]byte, []int) {
	return file_proto_public_todo_v1_todo_proto_rawDescGZIP(), []int{0}
}

func (x *ListTodosRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListTodosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todos         []*Todo                `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTodosResponse) Reset() {
	*x = ListTodosResponse{}
	mi := &file_proto_public_todo_v1_todo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTodosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTodosResponse) ProtoMessage() {}

func (x *ListTodosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_public_todo_v1_todo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTodosResponse.ProtoReflect.Descriptor instead.
func (*ListTodosResponse) Descriptor() ([]byte, []int) {
	return file_proto_public_todo_v1_todo_proto_rawDescGZIP(), []int{1}
}

func (x *ListTodosResponse) GetTodos() []*Todo {
	if x != nil {
		return x.Todos
	}
	return nil
}

type Todo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Completed     bool                   `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Todo) Reset() {
	*x = Todo{}
	mi := &file_proto_public_todo_v1_todo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Todo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Todo) ProtoMessage() {}

func (x *Todo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_public_todo_v1_todo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Todo.ProtoReflect.Descriptor instead.
func (*Todo) Descriptor() ([]byte, []int) {
	return file_proto_public_todo_v1_todo_proto_rawDescGZIP(), []int{2}
}

func (x *Todo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Todo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Todo) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *Todo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Todo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_proto_public_todo_v1_todo_proto protoreflect.FileDescriptor

const file_proto_public_todo_v1_todo_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/public/todo/v1/todo.proto\x12\x0epublic.todo.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"(\n" +
	"\x10ListTodosRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"?\n" +
	"\x11ListTodosResponse\x12*\n" +
	"\x05todos\x18\x01 \x03(\v2\x14.public.todo.v1.TodoR\x05todos\"\xc0\x01\n" +
	"\x04Todo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1c\n" +
	"\tcompleted\x18\x03 \x01(\bR\tcompleted\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2_\n" +
	"\vTodoService\x12P\n" +
	"\tListTodos\x12 .public.todo.v1.ListTodosRequest\x1a!.public.todo.v1.ListTodosResponseBEZCgithub.com/arrebole/vibe-coding-starter/proto/public/todo/v1;todov1b\x06proto3"

var (
	file_proto_public_todo_v1_todo_proto_rawDescOnce sync.Once
	file_proto_public_todo_v1_todo_proto_rawDescData []byte
)

func file_proto_public_todo_v1_todo_proto_rawDescGZIP() []byte {
	file_proto_public_todo_v1_todo_proto_rawDescOnce.Do(func() {
		file_proto_public_todo_v1_todo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_public_todo_v1_todo_proto_rawDesc), len(file_proto_public_todo_v1_todo_proto_rawDesc)))
	})
	return file_proto_public_todo_v1_todo_proto_rawDescData
}

var file_proto_public_todo_v1_todo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_public_todo_v1_todo_proto_goTypes = []any{
	(*ListTodosRequest)(nil),      // 0: public.todo.v1.ListTodosRequest
	(*ListTodosResponse)(nil),     // 1: public.todo.v1.ListTodosResponse
	(*Todo)(nil),                  // 2: public.todo.v1.Todo
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_proto_public_todo_v1_todo_proto_depIdxs = []int32{
	2, // 0: public.todo.v1.ListTodosResponse.todos:type_name -> public.todo.v1.Todo
	3, // 1: public.todo.v1.Todo.created_at:type_name -> google.protobuf.Timestamp
	3, // 2: public.todo.v1.Todo.updated_at:type_name -> google.protobuf.Timestamp
	0, // 3: public.todo.v1.TodoService.ListTodos:input_type -> public.todo.v1.ListTodosRequest
	1, // 4: public.todo.v1.TodoService.ListTodos:output_type -> public.todo.v1.ListTodosResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_public_todo_v1_todo_proto_init() }
func file_proto_public_todo_v1_todo_proto_init() {
	if File_proto_public_todo_v1_todo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_public_todo_v1_todo_proto_rawDesc), len(file_proto_public_todo_v1_todo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_public_todo_v1_todo_proto_goTypes,
		DependencyIndexes: file_proto_public_todo_v1_todo_proto_depIdxs,
		MessageInfos:      file_proto_public_todo_v1_todo_proto_msgTypes,
	}.Build()
	File_proto_public_todo_v1_todo_proto = out.File
	file_proto_public_todo_v1_todo_proto_goTypes = nil
	file_proto_public_todo_v1_todo_proto_depIdxs = nil
}
